stages:
  - test
  # - trigger_jenkins
  - build
  - deploy

variables:
  DOTNET_VERSION: 8.0
  VM_USER: "namson023"
  VM_HOST: "book-hive.space"
  DEPLOY_PATH: "/var/www/plsh-fe-librarian"

before_script:
  - mkdir -p ~/.ssh
  - eval "$(ssh-agent -s)"
  - 'echo "$DEPLOY_SSH_PRIVATE_KEY" > ~/.ssh/google_compute_engine'
  - chmod 600 ~/.ssh/google_compute_engine
  - ssh-add ~/.ssh/google_compute_engine
  - ssh-keyscan -H $VM_HOST >> ~/.ssh/known_hosts
  - ssh-keyscan -H 34.46.22.160 >> ~/.ssh/known_hosts
  - ssh-keyscan -H 34.67.95.8 >> ~/.ssh/known_hosts
  - apt-get update && apt-get install -y zip

# trigger_jenkins_job:
#   stage: trigger_jenkins
#   tags:
#     - jenkins-runner
#   script:
#     - echo "Triggering Jenkins pipeline..."
#     - curl -X POST "http://admin:1185d90d52dbdf516a3a0d5ac9ae4abf22@192.168.230.99:8080/job/Lab_iap491/job/G76_SEP490_SPR25_/job/plsh-fe-borrower/buildWithParameters?GIT_BRANCH=$CI_COMMIT_REF_NAME"


build_plsh-fe-librarian:
  stage: build
  image: node:20.18.3
  script:
    - echo "Installing dependencies..."
    - cd ./plsh-fe-librarian
    - echo "NEXT_PUBLIC_SERVER_API_URL=$NEXT_PUBLIC_SERVER_API_URL" >> .env
    - echo "NEXT_PUBLIC_STATIC_FILE_SERVER_API_URL=$NEXT_PUBLIC_STATIC_FILE_SERVER_API_URL" >> .env
    - echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
    - echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
    - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
    - cat .env
    - corepack enable
    - yarn install
    - echo "Building Next.js..."
    - yarn build
    - echo "Removing Next.js cache..."
    - rm -rf .next/cache
    - echo "Creating deployment package..."
    - zip -r next-app.zip .next package.json yarn.lock public
    - ls -lah
    

  artifacts:
    paths:
      - ./plsh-fe-librarian/next-app.zip
    expire_in: 1 hour
  only:
    - merge_requests
    - client/librarian/develop

deploy_plsh-fe-librarian:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - scp -o StrictHostKeyChecking=no ./plsh-fe-librarian/next-app.zip namson023@34.67.95.8:/home/namson023/next-app/
    - ssh -o StrictHostKeyChecking=no namson023@34.67.95.8 "bash -l -c 'cd /home/namson023/next-app && unzip -o next-app.zip'"
    - ssh -o StrictHostKeyChecking=no namson023@34.67.95.8 "bash -l -c 'source ~/.nvm/nvm.sh && cd /home/namson023/next-app && yarn install --production && (pm2 restart next-app || pm2 start yarn --name next-app -- run start)'"
    - ssh -o StrictHostKeyChecking=no namson023@34.67.95.8 "rm -f /home/namson023/next-app/next-app.zip"

  only:
    - merge_requests
    - client/librarian/develop



build_plsh-fe-borrower:
  stage: build
  image: node:20.18.3
  script:
    - echo "Installing dependencies..."
    - cd ./plsh-fe-borrower
    - echo "NEXT_PUBLIC_SERVER_API_URL=$NEXT_PUBLIC_SERVER_API_URL" >> .env
    - echo "NEXT_PUBLIC_STATIC_FILE_SERVER_API_URL=$NEXT_PUBLIC_STATIC_FILE_SERVER_API_URL" >> .env
    - echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
    - echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
    - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
    - cat .env
    - corepack enable
    - yarn install
    - echo "Building Next.js..."
    - yarn build
    - echo "Removing Next.js cache..."
    - rm -rf .next/cache
    - echo "Creating deployment package..."
    - zip -r next-app.zip .next package.json yarn.lock public
    - ls -lah
    

  artifacts:
    paths:
      - ./plsh-fe-borrower/next-app.zip
    expire_in: 1 hour
  only:
    - merge_requests
    - client/borrower/develop

deploy_plsh-fe-borrower:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - scp -o StrictHostKeyChecking=no ./plsh-fe-borrower/next-app.zip namson023@34.46.22.160:/home/namson023/next-app/
    - ssh -o StrictHostKeyChecking=no namson023@34.46.22.160 "bash -l -c 'cd /home/namson023/next-app && unzip -o next-app.zip'"
    - ssh -o StrictHostKeyChecking=no namson023@34.46.22.160 "bash -l -c 'source ~/.nvm/nvm.sh && cd /home/namson023/next-app && yarn install --production && (pm2 restart next-app || pm2 start yarn --name next-app -- run start)'"
    - ssh -o StrictHostKeyChecking=no namson023@34.46.22.160 "rm -f /home/namson023/next-app/next-app.zip"

  only:
    - merge_requests
    - client/borrower/develop


build_be:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: build
  script:
    - cd ./PLSH-BE
    - dotnet clean ./PLSH-BE.sln
    - dotnet restore PLSH-BE.sln
    - dotnet build ./PLSH-BE.sln -c Release
    - dotnet publish ./API/API.csproj -c Release -o ./publish --self-contained false
 
  artifacts:
    paths:
      - PLSH-BE/publish
    expire_in: 1 hours 
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "server/develop"'
      when: always



deploy_be:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - 'echo "$DEPLOY_SSH_PRIVATE_KEY" > ~/.ssh/google_compute_engine'
    - chmod 600 ~/.ssh/google_compute_engine
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/google_compute_engine
    - ssh-keyscan -H 34.70.225.68 >> ~/.ssh/known_hosts
  
  script:
    - cd ./PLSH-BE
    - echo "Deploying application to server"
    - ls ./publish
    - scp -o StrictHostKeyChecking=no -r ./publish/* namson023@34.70.225.68:/var/www/PLBH_App/
    - ssh -o StrictHostKeyChecking=no namson023@34.70.225.68 "sudo systemctl restart PLBH_App.service"
  environment:
    name: production
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "server/develop"'
      when: always
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

